### ISSUE TITLE
Ability to tail logs without refresh

### ISSUE THREAD

**Issue by robinovitch61** [robinovitch61/wander#1]
I'm thinking that while on the logs page, the keyhelp that shows up at the top of the page shows `f  tail logs`

Once `f` is pressed, a `tailing` indicator shows up to the right of the filter. Pressing `f` again turns it off.

Log offsets will need to be tracked, and we'll need to stop using the `"plain":  "true",` param in the current `FetchLogs` impl. There will probably need to be another nomad helper function that returns a suitable stream data structure rather than the full buffer read that currently occurs with `nomad.Get`

**Comment by courtland** [comment]
Came here to inquire about this feature. FWIW it's a great idea!

**Comment by robinovitch61** [comment]
@courtland thanks for the input! I'm sort of waiting for people to ask for things in order to prioritize them, so appreciate it :) i'll bump this up in the queue

**Comment by robinovitch61** [comment]
Released in v0.9.0

**Comment by courtland** [comment]
@robinovitch61 it works really great. Thank you!
