### ISSUE TITLE
CTR+C  should follow unix conventions and not exit wander

### ISSUE THREAD

**Issue by qwo** [robinovitch61/wander#100]
**Describe the bug**

When a user is using Wander exec, after you exec into a nomad job, I expect when I hit CTR+C; I expect to go up one level back to my list of jobs; This is the behavior in UNIX such as in processes like TMUX,.

However, when I hit CTR+Q or Q, it exits nomad all together.

**To reproduce**

Press Q or CTR+C in the exec service view. example here 

![Screenshot 2023-09-22 at 1 53 02 PM](https://github.com/robinovitch61/wander/assets/3683993/32fe63dc-06f5-4682-b626-60f3a204ab20)

**Expected behavior**

I expect that this would go up one level and back to the wander view one level up for job container, or the process list

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. iOS, Windows]
 - Terminal [e.g. iterm2]
 - Version [e.g. v0.5.1 or how it was installed if "built from source"]
 - Configuration options used, e.g. cli arguments, env vars, and/or `.wander.yaml` file

**Additional context**

**Comment by qwo** [comment]
Question is, can it be possible to split CTR+C and the QUIT process to two different actions. 

Quit to exit wander all together; CTR+C to go up a process level?

**Comment by robinovitch61** [comment]
Will be solved in next release!

**Comment by robinovitch61** [comment]
Released in v0.12.0
