### ISSUE TITLE
Default View starting Wander should be the filter view 

### ISSUE THREAD

**Issue by qwo** [robinovitch61/wander#101]
**Is your feature request related to a problem? Please describe.**
When I enter wander, as a user I begin to type the name of the Wander Job I want, I hit different keyboard keys when I type a job like "my-super-critical-app" where the letters are taken as keyboard navigation events. 

I then remember I have to hit `/`. 

This is similar to the experience with `vi` or `vim` where the user needs to remember or learn about insert mode `i`. 

**Describe the solution you'd like**

When I enter wander, as a user I begin to type the name of the Wander Job I want. 
As a user I begin typing the nomad job I want and expect it to filter so I can hit enter. 

**Describe alternatives you've considered**

**Additional context**

it might be confusing because if its default filter, entering filter mode might be confusing 

![image](https://github.com/robinovitch61/wander/assets/3683993/cbef26a7-022d-4671-a79e-e0af3beea051)

**Comment by robinovitch61** [comment]
> Let me know if you find that reasonable.

Going to assume yes, @qwo :)

**Comment by robinovitch61** [comment]
Will be included in next release with `--start-filtering`/`WANDER_START_FILTERING=true`/`wander_start_filtering: True` (defaults False)

**Comment by robinovitch61** [comment]
Released in v0.12.0
