### ISSUE TITLE
Add Allocs page enabling Jobs -> Allocs -> Tasks flow.

### ISSUE THREAD

**Issue by cshintov** [robinovitch61/wander#127]
**Is your feature request related to a problem? Please describe.**
I'm running my blockchain nodes on Nomad and many chains are run with many sidecars (tasks) together.
My interaction with them is always focused on a particular alloc and particular task. They're pets and not cattle.

![tasks-allocs-merged-view](https://github.com/robinovitch61/wander/assets/11365900/711abaf3-01f3-4dcf-84a2-d58b5f199089)

![focused-on-single-alloc](https://github.com/robinovitch61/wander/assets/11365900/dae13ba0-3188-4e23-a902-85450e04046b)

Hence I value the ability to focus on Allocs and then Tasks associated with it. The merged view is distracting and
requires extra work to filter out the noise.

**Describe the solution you'd like**
If I can drill down from Jobs -> Allocs -> Tasks, it would be a great UX.
Peace of mind, less noise.

**Describe alternatives you've considered**
I can use the filter, but it's not as intuitive as the drill down. Besides, it has a nagging bug; after the initial filter
if I move to next filtered row, after the tick, the selection jumps back to the first filtered row. Also it doesn't hide
the unfiltered rows.

But even if the filter works perfectly, it's not as intuitive as the drill down.

**Additional context**
I've played around and implemented the drill down version along with alloc restart in in #126. Would be great to have it in the mainline.

**Comment by cshintov** [comment]
@robinovitch61 @attachmentgenie

What do you guys think?

**Comment by robinovitch61** [comment]
Thanks for opening this for discussion @cshintov . To summarize, wander currently has 2 levels of drill-down: 1) jobs and 2) allocations and tasks combined in one table. This proposal would change that to 3 levels: 1) jobs, 2) allocations and 3) tasks, more similar to the web ui's model.

I'm interested in getting more data before proceeding with this change, as I personally see the 2 level model as an advantage, but am open to shifting to 3 level if there's broader support.

> it has a nagging bug; after the initial filter if I move to next filtered row, after the tick, the selection jumps back to the first filtered row

Ah, that's super annoying behavior! Broke it out into a bug issue here: https://github.com/robinovitch61/wander/issues/128

> Also it doesn't hide the unfiltered rows.

If you run wander with `--filter-with-context=false` or the equivalent env var/config option, it will only show matching rows

> implemented the drill down version along with alloc restart in in https://github.com/robinovitch61/wander/pull/126

If you want to extract out the alloc restart functionality and PR just that against `next` right now in a separate PR, we should be able to get that merged quickly regardless of the outcome of this drill-down discussion!

**Comment by robinovitch61** [comment]
@coderigo @classabbyamp @qwo @viniciusartur @Antse @sheridanvk @ghthor @yuankaiyu @hoppel @chuckyz @foozmeat @neomantra @bbarg @dbalan @beakman @moyiz ,

You've all contributed to or opened issues in wander before. Assuming you are or were users of it, what do you think of this proposal:

> wander currently has 2 levels of drill-down: 1) jobs and 2) allocations and tasks combined in one table. This proposal would change that to 3 levels: 1) jobs, 2) allocations and 3) tasks, more similar to the web ui's model

**Comment by ghthor** [comment]
I'm personally a fan of the existing drill down levels, though I haven't run into a case as the OP where it is hindering any of my workflows.

My question to the @cshintov. If you could group/sort by the alloc ID in the combined view, would that improve your workflow? That's an additional sorting mode, where the current sorting mode is based on the task name only.

**Comment by coderigo** [comment]
I too like the current drill-down levels, I don't know that layering it one
extra level adds much from when I've used it as by the time I get to a job
things tend to easily fit on one screen without paginating and it's obvious
which alloc belongs to which task.

**Comment by cshintov** [comment]
> My question to the @cshintov. If you could group/sort by the alloc ID in the combined view, would that improve your workflow? That's an additional sorting mode, where the current sorting mode is based on the task name only.

Ya, this could work if combined with `--filter-with-context=false`, **but still more work - more key presses and brain cycles**.

**Comment by cshintov** [comment]
> If you want to extract out the alloc restart functionality and PR just that against next right now in a separate PR, we should be able to get that merged quickly regardless of the outcome of this drill-down discussion!

👍

**Comment by neomantra** [comment]
Although I understand why the Web GUI is that way, I find myself jumping a lot between the Alloc/Task windows in the Web GUI.  And very often I want to check out the `alloc` files but that's not directly available from the `task` so you have to jump around, etc.     But then for an alloc you often need some minor task info and need to pop into the task page.

So I like how `wander` does it currently, but I don't have as many allocs/tasks as OP.

I thus appreciate that one drills down from Allocs into a Task; but I'd still want the current display at the Alloc level.

The power of TUI is that you can get to the where you want very easily -- enter/escape into a Task view is consistent with this.   That said, if a filter/sort helps achieve the same, then that might be simpler.

Is there any particular content/UX in a Task pane that would be different than the Alloc-focused pane?  In OPs example, they look identical.

**Comment by robinovitch61** [comment]
> I thus appreciate that one drills down from Allocs into a Task; but I'd still want the current display at the Alloc level.

This is a great idea. What if we sorted such that the "all tasks for job" page's first rows were the first task in each allocation, eg

Alloc A    Task 1
Alloc B    Task 1
Alloc C    Task 1
Alloc A    Task 2
...

And pressing "t" on one of these rows brings you to a "tasks only for this allocation" page. Do you think this is a nice middleground @cshintov ?

**Comment by cshintov** [comment]
> So I like how wander does it currently, but I don't have as many allocs/tasks as OP.

I think this is the reason why I want a focused view, and others don't. At small numbers (without many sidecars) it doesn't matter much. 

Ya, the above proposal might work, but I don't think it's needed, because without `filter with context` there's already a middle ground.

But if the majority of users are fine with the current view, it's OK. 

Besides, I can maintain my own version for my use case; that's the beauty and purpose of open source, isn't it?

**Comment by neomantra** [comment]
| Besides, I can maintain my own version for my use case; that's the beauty and purpose of open source, isn't it?

The other beauty is that the openness allows us to have broader awareness so that we can all be more powerful together.   I certainly want large Nomad installations to exist and operate well, even though I don't have a large one myself...

If you do experiment with your idea and make a PR or fork, please note it on this issue =)

**Comment by robinovitch61** [comment]
Sweet, thanks all for the discussion here. Sounds like `--filter-with-context=false` is a good enough middle ground for now. I'd be happy to add the "t for allocation-specific tasks" implementation [here](https://github.com/robinovitch61/wander/issues/127#issuecomment-1930494251) if desired in the future, but will close this issue for now as it seems like no one needs it yet. Anyone feel free to reopen or open a new issue referencing this one if you want to.

**Comment by cshintov** [comment]
@neomantra 

> If you do experiment with your idea and make a PR or fork, please note it on this issue =)

I had first raised the PR and then opened the issue 🙂
You can find it here: #126

**Comment by cshintov** [comment]
Glad to hear that you loved Kerala. Seems like you are fond of India. Your profile pic, the handle, etc! 🙏
