### ISSUE TITLE
Search selection jumps back to first result on page reload/refresh

### ISSUE THREAD

**Issue by robinovitch61** [robinovitch61/wander#128]
**Describe the bug**
Search selection jumps back to first result on page reload/refresh

**To reproduce**
Run `wander -u 1` in "filter with context" mode on (the default), filter for results, hit `n` to see the next result, and wait. Selection will jump back on page refresh

**Expected behavior**
Filter selection should be preserved after refresh to the best ability (if result disappears on refresh, should be as close as possible to result)

**Additional context**
Reported in https://github.com/robinovitch61/wander/issues/127

**Comment by robinovitch61** [comment]
@cshintov this should be fixed in `next` (`go install github.com/robinovitch61/wander@next`) now. Mind giving it a shot when you get the chance and letting me know if there is any other undesirable behavior?

**Comment by cshintov** [comment]
Just checked it works 🎉

**Comment by robinovitch61** [comment]
Fixed in v1.1.0
