### ISSUE TITLE
Option to "exec shell" in the allocation view

### ISSUE THREAD

**Issue by bbarg** [robinovitch61/wander#18]
As a `wander` user, I want an option to enter a bash shell on a running job/allocation from the logs view.

<img width="1059" alt="Screen Shot 2022-05-26 at 1 41 45 PM" src="https://user-images.githubusercontent.com/4207059/170545279-4df3b524-aa8e-419c-9f9a-40c210f964c6.png">

Ideally, there should be an additional option added to the list at the top of this page that opens a shell. This is basically re-implementing the "Exec" feature of the on nomad's `/ui/jobs` endpoint.

**Comment by robinovitch61** [comment]
Thanks for the issue @bbarg ! This is my next top priority, captured in #3 :)

My current thinking that pressing `s` on the allocations page will drop you into a shell on that allocation, rather than from the logs page of the allocation. Does that make sense do you think?

**Comment by robinovitch61** [comment]
Closed by https://github.com/robinovitch61/wander/pull/34
