### ISSUE TITLE
Goreleaser support for releases and homebrew

### ISSUE THREAD

**Issue by neomantra** [robinovitch61/wander#33]
[Goreleaser](https://goreleaser.com) is a really great tool for releasing Go projects.  I also note its author works at Charm.

By adopting a `.goreleaser.yml` file and a GitHub action, the `wander` project could be automatically built every push... and upon semantic version tags like `v0.1.1`, a GitHub Release and a Homebrew tap can easily be supported.  There are other release targets like Debian packages, but homebrew is pretty great for CLI tools.

I committed [a branch to my wander fork](https://github.com/neomantra/wander/tree/nm-goreleaser) which does the above.  However some aspects are hard-coded to my `neomantra` GitHub account, so I have not made a PR yet.

Links to the main blobs:
 * [`.goreleaser.yml`](https://github.com/neomantra/wander/blob/nm-goreleaser/.goreleaser.yml)
 * [`.github/workflows/release.yml`](https://github.com/neomantra/wander/blob/nm-goreleaser/.github/workflows/release.yml)

You can see the branch build and tag builds here:
https://github.com/neomantra/wander/actions

I tagged a `v0.0.1`... you can see the resultant release, with auto-Changelog here:
https://github.com/neomantra/wander/releases

And you can see my homebrew tap was updated here:
https://github.com/neomantra/homebrew-github/commit/413bed1609ab5de07d5ec6f4f48d77e4dc82917b

You can do the following to install:
```
brew tap neomantra/homebrew-github
brew install wander
```

Doing Homebrew support requires a Homebrew repo.... if you don't want to support that we can remove it.  You must set the secret `HOMEBREW_TAP_GITHUB_TOKEN` on your wander repo; it is an access token which can affect that Homebrew repo.

Let me know if you have questions...

**Comment by robinovitch61** [comment]
Hey @neomantra, thanks so much for laying this out! It feels like a good path forward on first blush. Semantic version tags and homebrew support are good priorities for me. Will dig deeper this weekend and shoot any questions your way.

**Comment by robinovitch61** [comment]
Hey @neomantra, will the github action run on every commit on every branch?

**Comment by neomantra** [comment]
As set up on my repo now, yes, every branch **builds** (as a “snapshot”).  However, only semantic version tags are released and homebrewed.

**Comment by robinovitch61** [comment]
Ah I see! Looks like the goreleaser action includes
```
No tag found for commit '31d8ec7'. Snapshot forced
```
Then adds `--snapshot` to the `goreleaser release` command. Great!

**Comment by robinovitch61** [comment]
I think this all worked great @neomantra ! Thanks for making it so clear and easy.

As a follow up, probably in separate issue, I'd like to make `wander --version` output either the installed semantic version and/or commit hash. Let me know if you have any ideas off the top of your head for that, otherwise I'll look into ways folks approach it.

Closing this issue as goreleaser, github releases, and a homebrew tap are now supported

**Comment by robinovitch61** [comment]
Figured out the `version` thing using ldflags :) 
<img width="279" alt="2022-06-26_15-12-00" src="https://user-images.githubusercontent.com/8892054/175835687-212d5d27-4093-4bee-a01c-07530840b6f2.png">

**Comment by robinovitch61** [comment]
Figured out the `version` thing using ldflags :)
![Uploading 2022-06-26_15-13-38.png…]()
