### ISSUE TITLE
Consider using NOMAD_ config prefixes instead of WANDER_ config prefixes to match nomad cli

### ISSUE THREAD

**Issue by robinovitch61** [robinovitch61/wander#50]
Inspired by comment on https://lobste.rs/s/b67kmz/wander_terminal_app_tui_for_hashicorp

> Why the choice to use different variables than the nomad cli tool itself?

At one point I had conflicts between them when wanting to point at a different cluster, so I decided to make an explicit config set specifically for wander. I can see how it might be a bit annoying given that 90% of users will have the same values for NOMAD_ADDR/WANDER_ADDR and NOMAD_TOKEN/WANDER_TOKEN.

I may want to change this in a backwards-compatible way so NOMAD_ prefixes are the recommended way. Maybe print a warning that the config names have changed and will be phased out in a later release.

Alternatively, maybe WANDER_ prefixes are better as they're explicitly for wander only and there will never be confusion with the CLI.

**Comment by foozmeat** [comment]
This would allow wander to work ootb for my users instead of wrapping with `wander -a $NOMAD_ADDR` etc.

**Comment by robinovitch61** [comment]
@foozmeat I'll get this released asap, thanks for the feedback!

**Comment by robinovitch61** [comment]
This should be fixed in v0.3.1 which is releasing now
