### ISSUE TITLE
Add an event stream tailer

### ISSUE THREAD

**Issue by chuckyz** [robinovitch61/wander#56]
It would be *incredibly useful* to have some form of event stream tailer, especially with the filtering as powerful as what's here now.

https://learn.hashicorp.com/tutorials/nomad/event-stream?in=nomad/nomad-1-0

**Comment by robinovitch61** [comment]
@chuckyz this is very cool, I didn't even know about this capability of Nomad. I'll definitely look at implementing this soon. Thanks for opening the issue!

**Comment by robinovitch61** [comment]
This is now available in v0.4.0 and up: https://github.com/robinovitch61/wander#tail-events

It's currently global, so doesn't matter what job you've selected when you press `e`, with configuration description here: https://github.com/robinovitch61/wander#configuration

See https://www.nomadproject.io/api-docs/events#event-stream for details on how to filter at the topic-job level using the config. Feel free to open follow-up issues with any other requests around this.

**Comment by chuckyz** [comment]
Will do!  I have some ideas right out of the gate.  Thank you for making such a wonderful tool!
