### ISSUE TITLE
TLS support for exec

### ISSUE THREAD

**Issue by hoppel** [robinovitch61/wander#64]
Using TLS for our cluster & it seems like there is no config options to specify the certificates required.

Wander just exits with `Error: Get "https://10.0.0.20:4646//v1/jobs?namespace=%2A": x509: certificate signed by unknown authority`

Official documentation regarding TLS for the CLI https://learn.hashicorp.com/tutorials/nomad/security-enable-tls#running-with-tls

**Comment by robinovitch61** [comment]
Thanks for opening this issue! Not having this yet is a miss on my part. I'll get it implemented soon for sure.

**Comment by robinovitch61** [comment]
@hoppel , I've added TLS support to the `next` branch for everything except `exec`ing into a cluster. That's proving a lot harder to port to the nomad api client than everything else, and I didn't want that to be a blocker to releasing the rest.

I'll release this in the next couple days, but if you'd like you can try it now with
```
go install github.com/robinovitch61/wander@next
```

Docs for new config options are here: https://github.com/robinovitch61/wander/tree/next#configuration

**Comment by hoppel** [comment]
Thank you! Works perfect so far.

`exec` does not work, wander exits with `Error: x509: certificate signed by unknown authority` which personally for me is not a deal breaker, just happy that all the other things are working.

**Comment by chuckyz** [comment]
@hoppel can you get around this by using `NOMAD_SKIP_VERIFY=true` ?  I *believe* if you run this locally the nomad API client should pick this up.

**Comment by robinovitch61** [comment]
> @hoppel can you get around this by using `NOMAD_SKIP_VERIFY=true` ? I _believe_ if you run this locally the nomad API client should pick this up.

Unfortunately I don't think this would work even if skip_verify would otherwise work, as no TLS parameters are passed to `exec` sessions today at all :(

Will be working on this soon to get full TLS param set passed to `exec` sessions

**Comment by andryyy** [comment]
Hey, can you look into this at some time? :) Would help a lot.

**Comment by robinovitch61** [comment]
@andryyy will do. Thanks for the input, good to know this would be useful for someone. The differences between my current implementation of exec and the nomad client API make this tricky, so might won't be immediate, but it's in the queue

**Comment by andryyy** [comment]
Thanks for you reply!

I don't want to sound demanding or something. It's totally fine if it's not worth the struggle, I would understand it. :)

**Comment by robinovitch61** [comment]
closing in favor of #107
