### ISSUE TITLE
Customizable event log format

### ISSUE THREAD

**Issue by yuankaiyu** [robinovitch61/wander#66]
The event log is a big piece of json, hard to read.
I'm wishing we can provide a jq query in config file and use that to transform the event log into information the user cares about.

Thanks for the great tool btw!

**Comment by robinovitch61** [comment]
Hi @yuankaiyu , thanks for opening an issue! This would be cool, and probably doable.

One workflow I could imagine today is saving the event log of interest with `ctrl + s`.

If you have `wander_copy_save_path` set to "true", the saved path will be copied to your clipboard on save.

Then you could run `cat <paste path> | jq <your query>`.

Probably still worth a native-in-wander solution. If you have a good idea for what default jq query for events might be best, let me know.

**Comment by yuankaiyu** [comment]
Ya I'd like to watch the events rolling.
The fields I'm interested in are topic, type, alloc id, task id etc. Probably a general queriability is better because the fields needed may change over time.
Thanks for the quick response!

**Comment by robinovitch61** [comment]
@yuankaiyu this feature is now merged to the `next` branch.

You can try it out with
```
go install github.com/robinovitch61/wander@next
```

By default, the jq query is:
```
wander_event_jq_query: >
  .Events[] | {
      "1:Index": .Index,
      "2:Topic": .Topic,
      "3:Type": .Type,
      "4:Name": .Payload | (.Job // .Allocation // .Deployment // .Evaluation) | (.JobID // .ID),
      "5:AllocID": .Payload | (.Allocation // .Deployment // .Evaluation).ID[:8]
  }
```

As mentioned in the README of `next`, the numbering exists to preserve ordering, as https://github.com/itchyny/gojq does not keep the order of object keys unfortunately.

Use the following to get back the previous behavior:
```
wander_event_jq_query: .
```

Feel free to experiment with the query in your config file and let me know if you have suggestions to improve the default query. I'll probably release this feature broadly sometime in the middle of this week.

**Comment by robinovitch61** [comment]
Closed in https://github.com/robinovitch61/wander/commit/1793de1a361ce207fdc6e7fa6b2e1c43755cbdb3

Upgrade to >=v0.8.0 to use this feature
