### ISSUE TITLE
Watching logs results in nil pointer exception

### ISSUE THREAD

**Issue by ghthor** [robinovitch61/wander#81]
**Describe the bug**

Watching logs of an allocation using follow is causing a nil pointer exception.

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x95195c]

goroutine 785 [running]:
github.com/robinovitch61/wander/internal/tui/nomad.ReadLogsStreamNextMessage.func1()
	/home/ghthor/go/pkg/mod/github.com/robinovitch61/wander@v0.9.0/internal/tui/nomad/logs.go:106 +0x3c
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6.1()
	/home/ghthor/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:470 +0x33
created by github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6
	/home/ghthor/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:468 +0x14d
exit status 2

```

**To reproduce**
1. Follow the logs of an allocation
2. Perform a deployment that will cause that allocation to be stopped
3. See error

I believe this is the reproduction, but I haven't confirmed as yet. I've seen it twice now, but I was iterating on something else and didn't go intentionally reproduce.

**Expected behavior**
Return to the allocations page?
OR Post to the logs that the allocation has been stopped maybe?

**Screenshots**

![Screenshot_2023-02-14_00-49-37](https://user-images.githubusercontent.com/160298/218650780-47649319-dbff-4428-910b-0a102680fe2a.png)

**Please complete the following information:**
 - OS: linux
 - Terminal: xfce4-terminal
 - Version: 0.9 built from source
 - Configuration options: none

**Additional context**

**Comment by robinovitch61** [comment]
Good catch! Thanks for the thorough report

**Comment by ghthor** [comment]
I've haven't been able to consistently recreate it, might be data race after and allocation has been stopped/replaced?

**Comment by robinovitch61** [comment]
Yea, I can't repro either :/. Yea or maybe a connection timeout of some sort. There are definitely things I could do to guard against this better, and I'll keep messing around to see if I can repro too. Let me know if you find a way to do so.

**Comment by robinovitch61** [comment]
Since I haven't been able to repro this, I'm going to close! Let me know if anyone gets a reliable repro going.
