### ISSUE TITLE
Running a long-running script using the exec function appears to timeout

### ISSUE THREAD

**Issue by sheridanvk** [robinovitch61/wander#82]
**Describe the bug**
When running a long-running script in a nomad container via the wander exec feature, the session timed out twice in a row with the below message. Unfortunately I can't be sure how long the timeout took to happen, but it was roughly no more than 10min.

**To reproduce**
1. Exec into a container
2. Run a long running script (mine was a python script)
3. Observe this message popping up after a few minutes:
```
Error: websocket: close sent

if this seems wrong, consider opening an issue here: https://github.com/robinovitch61/wander/issues/new/choose

q/ctrl+c to quit
```

**Expected behavior**
Connection should stay open until I choose to exit. FWIW this script was regularly printing logs to stdout every 20s or so. I can't find a truly reproducible case but will keep an eye out!

**Please complete the following information:**
 - OS: MacOS Ventura 13.0
 - Terminal: zsh
 - Version: v0.9.0
 - Configuration options used, e.g. cli arguments, env vars, and/or `.wander.yaml` file: None

**Comment by robinovitch61** [comment]
Thanks for this @sheridanvk ! I'll see if I can get a repro going and fix

**Comment by robinovitch61** [comment]
Since I haven't been able to repro this, I'm going to close! Let me know if anyone gets a reliable repro going.
