### ISSUE TITLE
Edit the job specs and restart a deployment

### ISSUE THREAD

**Issue by Antse** [robinovitch61/wander#83]
**Describe the solution you'd like**
Currently we can view a job spec by typing `p` in wander.

That would be great if we can edit the specs and plan a new allocation like in the ui.

By the way, thanks for this amazing tool

**Comment by robinovitch61** [comment]
Hi Antse, thanks for opening the issue. I haven't worked on wander in the past little bit but hoping to get back to it soon. I'll try to implement this when I do!

**Comment by robinovitch61** [comment]
@Antse would this still be useful functionality to you? Is anyone else actively interested in this?

**Comment by robinovitch61** [comment]
Going to leave this out for now, let me know if it would be particularly desired and I can reconsider
