### ISSUE TITLE
Feature request: Full Screen mode / Hide headers / headless mode

### ISSUE THREAD

**Issue by viniciusartur** [robinovitch61/wander#84]
**Is your feature request related to a problem? Please describe.**

When I split my terminal horizontally, I would like to hide the headers (showing shortcuts and cluster information) because I have not so much space for this information frame.

**Describe the solution you'd like**

I would like a shortcut allowing to toggle the headers area on and off to maximize the table height.

To me, the only information being important at all time in the header is the context, so it may be a good idea to keep it in "full screen mode".

**Describe alternatives you've considered**

Other (harder) alternative should be a ctrl + and ctrl - to increase/decrease the area and adjust it ( please note there are always 3 empty lines above the title of the table)

I have no workaround for now and I deal with it by putting the terminals on a bigger screen or by lowering down the char size...

**Additional context**

Similar to https://github.com/derailed/k9s/issues/270

If unclear I'll provide more context

Off topic : Great Work for this wonderful app :clap: :+1:

**Comment by robinovitch61** [comment]
Hi @viniciusartur , thanks for opening the issue. I haven't worked on wander in the past little bit but hoping to get back to it soon. I'll try to implement this when I do! I think it's a great idea and would use it myself.

Would pressing `-` with control held down for compact mode and then `+` with control held down for regular mode make sense to you? I'll add an option to start sessions in compact mode as well.

**Comment by viniciusartur** [comment]
Sounds great, @robinovitch61.
A little digression: I was wondering that in k8s we can have a view of all pods in all namespaces, so if one pod is not healthy we can see the red color. This is good as we can use k8s as a dashboard to have a big picture of all pods. I was wondering if we could see all tasks in all namespaces in wander.

**Comment by robinovitch61** [comment]
> Sounds great, @robinovitch61.

Sweet.

> A little digression: I was wondering that in k8s we can have a view of all pods in all namespaces, so if one pod is not healthy we can see the red color. This is good as we can use k8s as a dashboard to have a big picture of all pods. I was wondering if we could see all tasks in all namespaces in wander.

Sounds reasonable! Opened a separate issue for tracking here https://github.com/robinovitch61/wander/issues/87

**Comment by robinovitch61** [comment]
Merged to `next`

**Comment by robinovitch61** [comment]
Released in v0.10.0
