### ISSUE TITLE
View for all tasks in all allocations

### ISSUE THREAD

**Issue by robinovitch61** [robinovitch61/wander#87]
From @viniciusartur :

> I was wondering that in k8s we can have a view of all pods in all namespaces, so if one pod is not healthy we can see the red color. This is good as we can use k8s as a dashboard to have a big picture of all pods. I was wondering if we could see all tasks in all namespaces in wander.

https://developer.hashicorp.com/nomad/api-docs/allocations#list-allocations

**Comment by robinovitch61** [comment]
@viniciusartur, question for you - this is the current flow of `wander`:

![wander_flow drawio](https://github.com/robinovitch61/wander/assets/8892054/05eb974f-626d-4ce6-8ccc-185fa9aa8ffc)


The red box is this new feature. I'm thinking capital-A from the Jobs page will bring you to a view much like the Allocations For Job page, but showing all allocations (and all their tasks) across all jobs instead.

Do you think there should be navigation possible from the All Allocations page, e.g. if you press enter, you go to the Task Logs, or maybe to the Allocations for Job page (for that task's Job)?

Additionally, wherever you go, where should hitting Escape take you back to - the All Allocations page?

Interested in your thoughts as a user! I'm undecided.

**Comment by viniciusartur** [comment]
As an user of k9s, my setup for managing a k8s across 3 environments (test, stage and prod) was having a window in Tilix with 3 terminals opened running `k9s --headless` in the view that shows all pods in all namespaces.
From that point, what was useful for me was checking logs, which can be done by pressing `l`.
Besides that, when a pod was not healthy it would show the red color, which was very useful to spot when something was wrong.
As an example in the attached screenshot, I'm running k3s and having the same env spread in 3 terminals like I just explained:
![Screenshot from 2023-06-28 20-20-52](https://github.com/robinovitch61/wander/assets/882211/2d021bfe-c852-4bb2-a54f-ec7c5979b2f4)

---

Regarding wander / Nomad, I would say that checking the events is also very important, so if there was a way to from all tasks, some pending tasks, then click on something and see all events, that would be awesome.  
It would make sense by clicking on ESC, it would go back to the list of All allocations. It's also like this in k9s.
I think you should give a try on spinning up a k3s and using k9s to compare how's the navigation of this all pods feature, so it may give you some hints as well.

**Comment by robinovitch61** [comment]
@viniciusartur awesome, I think that gives me enough to go off of:
* `A` from jobs page will show all tasks (default all namespaces, but only the configured namespace if configured)
* color the task rows based on status
* press `v` to view events filtered to that task
* press `enter` to view logs for the task
* press `e` to exec in to the task, `p` for spec, etc (same other commands as current allocations page)
* returning from logs/spec/exec/events brings you back to all tasks, not the tasks for just the job

RE: headless mode, making some progress on https://github.com/robinovitch61/wander/issues/84, will likely be included in next release within the next few weeks. Might not get all tasks view in that release but we'll see

**Comment by robinovitch61** [comment]
Something like this
![wander_flow drawio](https://github.com/robinovitch61/wander/assets/8892054/0996f781-dd15-4e03-ab46-a22fc0c4ad46)

**Comment by robinovitch61** [comment]
Released in v0.10.0, let me know how it goes :)

**Comment by viniciusartur** [comment]
It worked well, thanks! Great big picture of the cluster!
