### ISSUE TITLE
Configurable max column width

### ISSUE THREAD

**Issue by robinovitch61** [robinovitch61/wander#97]
Should not apply when wrap is on

**Comment by viniciusartur** [comment]
It would be possible to customize what columns should appear in the view? That would be helpful when I open multiple windows in my terminal for different Nomad environments (dev, test, prod).  
Also sorting by task state (dead, running), would be also useful.

**Comment by robinovitch61** [comment]
Check out the config file in the readme, I think that's already implemented :)

**Comment by robinovitch61** [comment]
Please open separate issues for other things (e.g. sorting by task state - should be doable but not implemented yet, please open a new issue)

**Comment by robinovitch61** [comment]
Going to close as won't do for now, if anyone would find this useful please ping me
